# Generated by Django 5.2.15 on 2026-06-08 17:23

import collection.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(blank=True, max_length=60)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CollectionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Unit or model name, e.g. 'Ballistus Dreadnought'.", max_length=200)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('assembly_state', models.PositiveSmallIntegerField(choices=[(0, 'New on sprue'), (10, 'Clipped'), (20, 'Assembled')], default=0)),
                ('paint_state', models.PositiveSmallIntegerField(choices=[(0, 'Unpainted'), (10, 'Primed'), (20, 'In progress'), (30, 'Painted'), (40, 'Based')], default=0)),
                ('paint_scheme', models.CharField(blank=True, max_length=160)),
                ('storage_location', models.CharField(blank=True, max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, max_length=255, null=True, upload_to=collection.models.collection_photo_path)),
                ('ready_for_game', models.BooleanField(default=False)),
                ('backlog_priority', models.PositiveSmallIntegerField(blank=True, choices=[(10, 'Low'), (20, 'Medium'), (30, 'High')], null=True)),
                ('faction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='reference.faction')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_entries', to=settings.AUTH_USER_MODEL)),
                ('subfaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='reference.subfaction', verbose_name='chapter / subfaction')),
                ('source_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='collection.sourceproduct')),
                ('tags', models.ManyToManyField(blank=True, related_name='entries', to='collection.tag')),
            ],
            options={
                'verbose_name_plural': 'collection entries',
                'ordering': ['-updated'],
            },
        ),
        migrations.AddIndex(
            model_name='sourceproduct',
            index=models.Index(fields=['owner'], name='collection__owner_i_3b419a_idx'),
        ),
        migrations.AddConstraint(
            model_name='sourceproduct',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='uniq_source_per_owner'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['owner'], name='collection__owner_i_f97216_idx'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='uniq_tag_name_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='uniq_tag_slug_per_owner'),
        ),
        migrations.AddIndex(
            model_name='collectionentry',
            index=models.Index(fields=['owner', 'faction'], name='collection__owner_i_06f69b_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionentry',
            index=models.Index(fields=['owner', 'subfaction'], name='collection__owner_i_58a91d_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionentry',
            index=models.Index(fields=['owner', 'assembly_state'], name='collection__owner_i_0ac77d_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionentry',
            index=models.Index(fields=['owner', 'paint_state'], name='collection__owner_i_4dff7d_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionentry',
            index=models.Index(fields=['owner', 'ready_for_game'], name='collection__owner_i_7b93b2_idx'),
        ),
        migrations.AddConstraint(
            model_name='collectionentry',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='entry_quantity_min_1'),
        ),
    ]
