# Generated by Django 5.2.15 on 2026-06-08 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GameSystemVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(help_text="Short stable id, e.g. 'new40k'.", max_length=40, unique=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Detachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detachments', to='reference.faction')),
                ('game_system_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detachments', to='reference.gamesystemversion')),
            ],
            options={
                'ordering': ['faction__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubFaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=60)),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subfactions', to='reference.faction')),
            ],
            options={
                'ordering': ['faction__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UnitCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('unit_type', models.CharField(blank=True, help_text='Battlefield role / unit type, free text for now.', max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='reference.faction')),
                ('game_system_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='units', to='reference.gamesystemversion')),
                ('keywords', models.ManyToManyField(blank=True, related_name='units', to='reference.keyword')),
            ],
            options={
                'ordering': ['faction__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UnitPointProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('model_count', models.PositiveSmallIntegerField(default=1)),
                ('points', models.PositiveIntegerField()),
                ('faq_update_date', models.DateField(blank=True, null=True)),
                ('game_system_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unit_point_profiles', to='reference.gamesystemversion')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_profiles', to='reference.unitcatalog')),
            ],
            options={
                'ordering': ['unit__name', 'model_count'],
            },
        ),
        migrations.CreateModel(
            name='DetachmentCostProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('points', models.PositiveIntegerField(default=0)),
                ('faq_update_date', models.DateField(blank=True, null=True)),
                ('detachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_profiles', to='reference.detachment')),
                ('game_system_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detachment_cost_profiles', to='reference.gamesystemversion')),
            ],
            options={
                'ordering': ['detachment__name'],
                'constraints': [models.UniqueConstraint(fields=('detachment', 'game_system_version'), name='uniq_detachment_cost_per_version')],
            },
        ),
        migrations.AddConstraint(
            model_name='detachment',
            constraint=models.UniqueConstraint(fields=('faction', 'name'), name='uniq_detachment_name_per_faction'),
        ),
        migrations.AddConstraint(
            model_name='subfaction',
            constraint=models.UniqueConstraint(fields=('faction', 'name'), name='uniq_subfaction_name_per_faction'),
        ),
        migrations.AddConstraint(
            model_name='subfaction',
            constraint=models.UniqueConstraint(fields=('faction', 'slug'), name='uniq_subfaction_slug_per_faction'),
        ),
        migrations.AddConstraint(
            model_name='unitcatalog',
            constraint=models.UniqueConstraint(fields=('faction', 'name'), name='uniq_unit_name_per_faction'),
        ),
        migrations.AddConstraint(
            model_name='unitpointprofile',
            constraint=models.UniqueConstraint(fields=('unit', 'game_system_version', 'model_count'), name='uniq_unit_points_per_version_count'),
        ),
    ]
